Print out full bt and locals

diff --git a/py-bt b/py-bt
--- a/py-bt
+++ b/py-bt
@@ -1,8 +1,4 @@
-#!/bin/bash
-if [[ $EUID > 0 ]]; then
-    exec sudo "$0" "$@"
-fi
-
+#!/bin/bash -x
 if [[ -z $1 ]]; then
     echo "Please specify a PID as the first argument to $0" >&2
     exit 1
@@ -11,5 +7,21 @@ else
     echo "Inspecting $PID ..." >&2
 fi
 
+PY_VER=`/proc/$PID/exe -c 'import sys; print("%d.%d" % (sys.version_info[0], sys.version_info[1]))'`
+if [[ -z $PY_VER ]]; then
+    echo "Could not determine which version of python $PID is using."
+    exit 1
+fi
 
-sudo gdb -q -p $PID -ex bt -ex quit </dev/null
+if ! dpkg -l python${PY_VER}-dbg >/dev/null; then
+    echo "Fetching debug packages..."
+    sudo apt-get -y install python${PY_VER}-dbg
+fi
+
+sudo gdb -q -p $PID -ex bt -ex 'printf "\n=============\n\n"' \
+  -ex py-locals \
+  -ex 'printf "\n=============\n\n"' \
+  -ex py-list \
+  -ex 'printf "\n=============\n\n"' \
+  -ex py-bt \
+  -ex quit </dev/null
